<?php
/**
 * Created by PhpStorm.
 * User: palad
 * Date: 03.06.2018
 * Time: 21:06
 */

namespace app\widgets;

use yii\grid\GridView;
use yii\base\Widget;

class CurrentTasks extends Widget
{
    public $date;
    public $user;

    public $dataProvider;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        echo GridView::widget([
        'dataProvider' => $this->dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'name',
            'date',
            'description:ntext',

            ['class' => 'yii\grid\ActionColumn'],
        ],
        ]);
    }
}