<?php
/**
 * Created by PhpStorm.
 * User: palad
 * Date: 17.06.2018
 * Time: 18:56
 */

namespace app\models\ActiveRecord;


use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class ActiveRecord extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            ['class' => TimestampBehavior::class,
                'createdAtAttribute' => 'date_of_create',
                'updatedAtAttribute' => 'date_of_update',
                'value' => new Expression('NOW()'),
            ],

        ]; // TODO: Change the autogenerated stub
    }
}