<?php
/**
 * Created by PhpStorm.
 * User: palad
 * Date: 26.05.2018
 * Time: 20:16
 */

namespace app\models;


use app\models\behaviors\MyBehavior;
use app\models\events\TestRunStartEvent;
use yii\base\Model;

class Test extends Model
{
    public $modelParam;

   const EVENT_RUN_START = 'run start';

   public function  Rules() {
       return [
           //['modelParam', 'safe']
       ];
   }

   public function run() {
       $this->trigger(static::EVENT_RUN_START, new TestRunStartEvent(['id' => 2]));

       echo 'Подготовка к началу работы <br>';
       echo 'Процесс запущен <br>';
       echo 'Подготовка к завершению <br>';
       echo 'Процесс завершен <br>';
   }

   public function behaviors()
   {
       return [
           'myBehavior' => [
               'class' => MyBehavior::class,
               'message' => 'Это поведение'
           ]
           //MyBehavior::class
       ];//parent::behaviors(); // TODO: Change the autogenerated stub
   }

}